Libbpf sync 2023 06 13 t17 50 39.365 z
libbpf/libbpf pull request #698
Opened 2023-06-13 18:36 UTC by chantra

2023-06-14 02:19 UTC, chantra commented
bpf_nf/tc-bpf-ct:FAIL
has been failing on both s390x and kernel LATEST test_progs_noalu32 since the last sync.
https://github.com/libbpf/libbpf/actions/runs/5085607205/jobs/9139233610 is the first time we see it so I would guess the issue started as we sync libbpf last time: https://github.com/libbpf/libbpf/pull/693

For some reason, it does not repro in kernel-patches/bpf, so not sure why that could be.

2023-06-14 02:19 UTC, chantra commented
More precisely, the error looks like:
```
2023-06-13T19:40:12.8750649Z test_bpf_nf_ct:PASS:test_bpf_nf__open_and_load 0 nsec
2023-06-13T19:40:12.8762711Z test_bpf_nf_ct:PASS:iptables-legacy -t raw -A PREROUTING -j CONNMARK --set-mark 42/0 0 nsec
2023-06-13T19:40:12.8765256Z test_bpf_nf_ct:PASS:start_server 0 nsec
2023-06-13T19:40:12.8770061Z connect_to_server:PASS:socket 0 nsec
2023-06-13T19:40:12.8773499Z connect_to_server:PASS:connect_fd_to_fd 0 nsec
2023-06-13T19:40:12.8778436Z test_bpf_nf_ct:PASS:connect_to_server 0 nsec
2023-06-13T19:40:12.8781124Z test_bpf_nf_ct:PASS:accept 0 nsec
2023-06-13T19:40:12.8784197Z test_bpf_nf_ct:PASS:sockaddr len 0 nsec
2023-06-13T19:40:12.8789265Z test_bpf_nf_ct:PASS:bpf_prog_test_run 0 nsec
2023-06-13T19:40:12.8793558Z test_bpf_nf_ct:PASS:Test EINVAL for NULL bpf_tuple 0 nsec
2023-06-13T19:40:12.8800894Z test_bpf_nf_ct:PASS:Test EINVAL for reserved not set to 0 0 nsec
2023-06-13T19:40:12.8805290Z test_bpf_nf_ct:PASS:Test EINVAL for netns_id < -1 0 nsec
2023-06-13T19:40:12.8812339Z test_bpf_nf_ct:PASS:Test EINVAL for len__opts != NF_BPF_CT_OPTS_SZ 0 nsec
2023-06-13T19:40:12.8818727Z test_bpf_nf_ct:PASS:Test EPROTO for l4proto != TCP or UDP 0 nsec
2023-06-13T19:40:12.8823546Z test_bpf_nf_ct:PASS:Test ENONET for bad but valid netns_id 0 nsec
2023-06-13T19:40:12.8829498Z test_bpf_nf_ct:PASS:Test ENOENT for failed lookup 0 nsec
2023-06-13T19:40:12.8834334Z test_bpf_nf_ct:PASS:Test EAFNOSUPPORT for invalid len__tuple 0 nsec
2023-06-13T19:40:12.8840069Z test_bpf_nf_ct:PASS:Test for alloc new entry 0 nsec
2023-06-13T19:40:12.8843960Z test_bpf_nf_ct:PASS:Test for insert new entry 0 nsec
2023-06-13T19:40:12.8854643Z test_bpf_nf_ct:FAIL:Test for successful lookup unexpected Test for successful lookup: actual -2 != expected 0
2023-06-13T19:40:12.8865471Z test_bpf_nf_ct:FAIL:Test for min ct timeout update unexpected Test for min ct timeout update: actual 0 <= expected 8
2023-06-13T19:40:12.8871354Z test_bpf_nf_ct:PASS:Test for max ct timeout update 0 nsec
2023-06-13T19:40:12.8886114Z test_bpf_nf_ct:FAIL:Test for insert and lookup mark value unexpected Test for insert and lookup mark value: actual 0 != expected 77
2023-06-13T19:40:12.8891933Z test_bpf_nf_ct:FAIL:Test for ct status update  unexpected Test for ct status update : actual 0 != expected 442
2023-06-13T19:40:12.8897516Z test_bpf_nf_ct:PASS:Test existing connection lookup 0 nsec
2023-06-13T19:40:12.8902276Z test_bpf_nf_ct:PASS:Test existing connection lookup ctmark 0 nsec
2023-06-13T19:40:12.8913037Z test_bpf_nf_ct:FAIL:Test for source natting unexpected Test for source natting: actual -22 != expected 0
2023-06-13T19:40:12.8926826Z test_bpf_nf_ct:FAIL:Test for destination natting unexpected Test for destination natting: actual -22 != expected 0
2023-06-13T19:40:12.8928744Z #17/2    bpf_nf/tc-bpf-ct:FAIL
2023-06-13T19:40:12.8932871Z #17      bpf_nf:FAIL
2023-06-13T19:40:12.8942079Z Summary: 366/3139 PASSED, 29 SKIPPED, 1 FAILED
```

2023-06-16 02:21 UTC, anakryiko requested changes
please use `ci: ` prefix for commits updating denylist, for consistent naming with other commits

2023-06-16 02:21 UTC, anakryiko commented on ci/vmtest/configs/DENYLIST-latest
> +bpf_nf/tc-bpf-ct # test consistently failing on x86: https://github.com/libbpf/libbpf/pull/698#issuecomment-1590341200
seems like we need to add `bpf_nf/xdp-ct` here as well?

2023-06-17 00:07 UTC, anakryiko approved these changes

2023-06-17 00:07 UTC, merged